// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// random_split_indices
List random_split_indices(int n, NumericVector split_weights);
RcppExport SEXP _RandomSplitter_random_split_indices(SEXP nSEXP, SEXP split_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type split_weights(split_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(random_split_indices(n, split_weights));
    return rcpp_result_gen;
END_RCPP
}
// stratified_split_indices
List stratified_split_indices(IntegerVector labels, NumericVector split_weights);
RcppExport SEXP _RandomSplitter_stratified_split_indices(SEXP labelsSEXP, SEXP split_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type split_weights(split_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(stratified_split_indices(labels, split_weights));
    return rcpp_result_gen;
END_RCPP
}
// sample_n
IntegerVector sample_n(int n);
RcppExport SEXP _RandomSplitter_sample_n(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_n(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RandomSplitter_random_split_indices", (DL_FUNC) &_RandomSplitter_random_split_indices, 2},
    {"_RandomSplitter_stratified_split_indices", (DL_FUNC) &_RandomSplitter_stratified_split_indices, 2},
    {"_RandomSplitter_sample_n", (DL_FUNC) &_RandomSplitter_sample_n, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RandomSplitter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
