# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_split_indices <- function(n, split_weights) {
    .Call(`_RandomSplitter_random_split_indices`, n, split_weights)
}

stratified_split_indices <- function(labels, split_weights) {
    .Call(`_RandomSplitter_stratified_split_indices`, labels, split_weights)
}

sample_n <- function(n) {
    .Call(`_RandomSplitter_sample_n`, n)
}

